include: package:very_good_analysis/analysis_options.5.1.0.yaml
linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
    sort_constructors_first: false
    lines_longer_than_80_chars: ignore
