name: pokebook
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  flutter:
    sdk: flutter

  # ui
  auto_size_text: ^3.0.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.7
  number_paginator: ^0.4.1
  palette_generator: ^0.3.3+3
  google_fonts: ^6.2.1
  toastification: ^1.2.1

  # state management
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  hydrated_bloc: ^9.1.4

  # services
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  auto_route: ^7.9.1
  dio: ^5.4.1
  get_it: ^7.6.7
  path_provider: ^2.1.2
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  sentry_flutter: ^7.18.0
  firebase_core: ^2.27.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  auto_route_generator: ^7.3.2
  bloc_test: ^9.1.6
  freezed: ^2.4.7
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
  json_serializable: ^6.7.1

flutter_gen:
  output: lib/data/assets/

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/cfg/
    - assets/svgs/
